spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        narive:
          search-locations: "classpath:/config"

server:
  port: 8071
